# AllCops:
#   Exclude:
#     - examples/*.rb
#     - test/**/*.rb

Metrics/LineLength:
  Max: 120

Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false
